<a href="https://colab.research.google.com/github/AkarshAnilkumar/AML-331-Python-and-Machine-Learning-Lab/blob/main/PYTHON/NumPy/_3ArraySlicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tutorial on Slicing an array

In [ ]:
#Slicing in python means taking elements from one given index to another given index excluding the latter index.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Taking only elements 
print(arr[1:6])

[2 3 4 5 6]


In [ ]:
#Slice elements from index 4 to the end of the array including mentioned element.
print(arr[4:])

[5 6 7]


In [ ]:
#Slice elements from the beginning to index 4 (not included)
print(arr[:4])

[1 2 3 4]


In [ ]:
#Use the minus operator to refer to an index from the end
import numpy as np
#Elements from 3rd last and last element excluding the last element...
print(arr[-3:-1])